name: AdminTools
main: com.gmail.ZiomuuSs.Main
version: 0.1
commands:
   AdminTools:
      aliases: [at, admin]
      description: Glowna komenda.
      usage: /at
   ClearChat:
      aliases: [cc]
      description: Czysci chat.
      usage: /cc
   ChujeWypusccieMnie:
      aliases: [wyjdz]
      description: Wypuszcza z eventu.
      usage: /wyjdz