name: AdminTools
main: com.gmail.ZiomuuSs.Main
version: 0.1
softdepend: [Multiverse-Core]
commands:
   AdminTools:
      aliases: [at, admin]
      description: Glowna komenda.
      usage: /at
   ClearChat:
      aliases: [cc]
      description: Czysci chat.
      usage: /cc
   Event:
      aliases: [e]
      description: Komenda gracza do eventu.
      usage: /e