name: AdminTools
main: com.gmail.ZiomuuSs.Main
version: 0.4
softdepend: [Multiverse-Core, LegacyFactions]
commands:
   AdminTools:
      aliases: [at, admin]
      description: Glowna komenda.
      usage: /at
   ClearChat:
      aliases: [cc]
      description: Czysci chat.
      usage: /cc
   Event:
      aliases: [e]
      description: Komenda gracza do eventu.
      usage: /e
   Vip:
      description: Wyswietla informacje o randze VIP.
      usage: /vip
   Svip:
      description: Wyswietla informacje o randze SVIP.
      usage: /svip
   Drop:
      description: Wyswietla drop.
      usage: /drop
   Komendy:
      description: Wyswietla komendy dostepne na serwerze.
      usage: /komendy
   Pomoc:
      description: Wyswietla pomoc.
      usage: /pomoc
   SetWarp:
      description: Ustawia nowy warp.
      usage: /setwarp
   Warp:
      description: Wyswietla liste warpow.
      usage: /warp